; Auto-generated. Do not edit!


(cl:in-package alice_msgs-msg)


;//! \htmlinclude aliceapproachResult.msg.html

(cl:defclass <aliceapproachResult> (roslisp-msg-protocol:ros-message)
  ((done
    :reader done
    :initarg :done
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass aliceapproachResult (<aliceapproachResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <aliceapproachResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'aliceapproachResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alice_msgs-msg:<aliceapproachResult> is deprecated: use alice_msgs-msg:aliceapproachResult instead.")))

(cl:ensure-generic-function 'done-val :lambda-list '(m))
(cl:defmethod done-val ((m <aliceapproachResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alice_msgs-msg:done-val is deprecated.  Use alice_msgs-msg:done instead.")
  (done m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <aliceapproachResult>) ostream)
  "Serializes a message object of type '<aliceapproachResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'done) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <aliceapproachResult>) istream)
  "Deserializes a message object of type '<aliceapproachResult>"
    (cl:setf (cl:slot-value msg 'done) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<aliceapproachResult>)))
  "Returns string type for a message object of type '<aliceapproachResult>"
  "alice_msgs/aliceapproachResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'aliceapproachResult)))
  "Returns string type for a message object of type 'aliceapproachResult"
  "alice_msgs/aliceapproachResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<aliceapproachResult>)))
  "Returns md5sum for a message object of type '<aliceapproachResult>"
  "89bb254424e4cffedbf494e7b0ddbfea")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'aliceapproachResult)))
  "Returns md5sum for a message object of type 'aliceapproachResult"
  "89bb254424e4cffedbf494e7b0ddbfea")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<aliceapproachResult>)))
  "Returns full string definition for message of type '<aliceapproachResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'aliceapproachResult)))
  "Returns full string definition for message of type 'aliceapproachResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <aliceapproachResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <aliceapproachResult>))
  "Converts a ROS message object to a list"
  (cl:list 'aliceapproachResult
    (cl:cons ':done (done msg))
))
