; Auto-generated. Do not edit!


(cl:in-package alice_msgs-msg)


;//! \htmlinclude aliceapproachFeedback.msg.html

(cl:defclass <aliceapproachFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass aliceapproachFeedback (<aliceapproachFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <aliceapproachFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'aliceapproachFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alice_msgs-msg:<aliceapproachFeedback> is deprecated: use alice_msgs-msg:aliceapproachFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <aliceapproachFeedback>) ostream)
  "Serializes a message object of type '<aliceapproachFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <aliceapproachFeedback>) istream)
  "Deserializes a message object of type '<aliceapproachFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<aliceapproachFeedback>)))
  "Returns string type for a message object of type '<aliceapproachFeedback>"
  "alice_msgs/aliceapproachFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'aliceapproachFeedback)))
  "Returns string type for a message object of type 'aliceapproachFeedback"
  "alice_msgs/aliceapproachFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<aliceapproachFeedback>)))
  "Returns md5sum for a message object of type '<aliceapproachFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'aliceapproachFeedback)))
  "Returns md5sum for a message object of type 'aliceapproachFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<aliceapproachFeedback>)))
  "Returns full string definition for message of type '<aliceapproachFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'aliceapproachFeedback)))
  "Returns full string definition for message of type 'aliceapproachFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <aliceapproachFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <aliceapproachFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'aliceapproachFeedback
))
