; Auto-generated. Do not edit!


(cl:in-package alice_msgs-msg)


;//! \htmlinclude alicecontrollerfunctionFeedback.msg.html

(cl:defclass <alicecontrollerfunctionFeedback> (roslisp-msg-protocol:ros-message)
  ((correct
    :reader correct
    :initarg :correct
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass alicecontrollerfunctionFeedback (<alicecontrollerfunctionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <alicecontrollerfunctionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'alicecontrollerfunctionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alice_msgs-msg:<alicecontrollerfunctionFeedback> is deprecated: use alice_msgs-msg:alicecontrollerfunctionFeedback instead.")))

(cl:ensure-generic-function 'correct-val :lambda-list '(m))
(cl:defmethod correct-val ((m <alicecontrollerfunctionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alice_msgs-msg:correct-val is deprecated.  Use alice_msgs-msg:correct instead.")
  (correct m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <alicecontrollerfunctionFeedback>) ostream)
  "Serializes a message object of type '<alicecontrollerfunctionFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'correct) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <alicecontrollerfunctionFeedback>) istream)
  "Deserializes a message object of type '<alicecontrollerfunctionFeedback>"
    (cl:setf (cl:slot-value msg 'correct) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<alicecontrollerfunctionFeedback>)))
  "Returns string type for a message object of type '<alicecontrollerfunctionFeedback>"
  "alice_msgs/alicecontrollerfunctionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'alicecontrollerfunctionFeedback)))
  "Returns string type for a message object of type 'alicecontrollerfunctionFeedback"
  "alice_msgs/alicecontrollerfunctionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<alicecontrollerfunctionFeedback>)))
  "Returns md5sum for a message object of type '<alicecontrollerfunctionFeedback>"
  "0d7b90c75811aaad705aac4e2b606238")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'alicecontrollerfunctionFeedback)))
  "Returns md5sum for a message object of type 'alicecontrollerfunctionFeedback"
  "0d7b90c75811aaad705aac4e2b606238")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<alicecontrollerfunctionFeedback>)))
  "Returns full string definition for message of type '<alicecontrollerfunctionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%bool correct~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'alicecontrollerfunctionFeedback)))
  "Returns full string definition for message of type 'alicecontrollerfunctionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%bool correct~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <alicecontrollerfunctionFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <alicecontrollerfunctionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'alicecontrollerfunctionFeedback
    (cl:cons ':correct (correct msg))
))
