; Auto-generated. Do not edit!


(cl:in-package alice_msgs-msg)


;//! \htmlinclude ObjectROIFeedback.msg.html

(cl:defclass <ObjectROIFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ObjectROIFeedback (<ObjectROIFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjectROIFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjectROIFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alice_msgs-msg:<ObjectROIFeedback> is deprecated: use alice_msgs-msg:ObjectROIFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjectROIFeedback>) ostream)
  "Serializes a message object of type '<ObjectROIFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjectROIFeedback>) istream)
  "Deserializes a message object of type '<ObjectROIFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjectROIFeedback>)))
  "Returns string type for a message object of type '<ObjectROIFeedback>"
  "alice_msgs/ObjectROIFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjectROIFeedback)))
  "Returns string type for a message object of type 'ObjectROIFeedback"
  "alice_msgs/ObjectROIFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjectROIFeedback>)))
  "Returns md5sum for a message object of type '<ObjectROIFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjectROIFeedback)))
  "Returns md5sum for a message object of type 'ObjectROIFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjectROIFeedback>)))
  "Returns full string definition for message of type '<ObjectROIFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjectROIFeedback)))
  "Returns full string definition for message of type 'ObjectROIFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjectROIFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjectROIFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjectROIFeedback
))
