; Auto-generated. Do not edit!


(cl:in-package alice_msgs-msg)


;//! \htmlinclude ObjectROIResult.msg.html

(cl:defclass <ObjectROIResult> (roslisp-msg-protocol:ros-message)
  ((roi
    :reader roi
    :initarg :roi
    :type (cl:vector alice_msgs-msg:ROI)
   :initform (cl:make-array 0 :element-type 'alice_msgs-msg:ROI :initial-element (cl:make-instance 'alice_msgs-msg:ROI))))
)

(cl:defclass ObjectROIResult (<ObjectROIResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjectROIResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjectROIResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alice_msgs-msg:<ObjectROIResult> is deprecated: use alice_msgs-msg:ObjectROIResult instead.")))

(cl:ensure-generic-function 'roi-val :lambda-list '(m))
(cl:defmethod roi-val ((m <ObjectROIResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alice_msgs-msg:roi-val is deprecated.  Use alice_msgs-msg:roi instead.")
  (roi m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjectROIResult>) ostream)
  "Serializes a message object of type '<ObjectROIResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'roi))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'roi))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjectROIResult>) istream)
  "Deserializes a message object of type '<ObjectROIResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'roi) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'roi)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'alice_msgs-msg:ROI))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjectROIResult>)))
  "Returns string type for a message object of type '<ObjectROIResult>"
  "alice_msgs/ObjectROIResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjectROIResult)))
  "Returns string type for a message object of type 'ObjectROIResult"
  "alice_msgs/ObjectROIResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjectROIResult>)))
  "Returns md5sum for a message object of type '<ObjectROIResult>"
  "e17122d90dfd682041714829c01ce576")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjectROIResult)))
  "Returns md5sum for a message object of type 'ObjectROIResult"
  "e17122d90dfd682041714829c01ce576")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjectROIResult>)))
  "Returns full string definition for message of type '<ObjectROIResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%ROI[] roi~%~%================================================================================~%MSG: alice_msgs/ROI~%int32 left ~%int32 top~%int32 right~%int32 bottom~%float32 x~%float32 y~%float32 z~%float32 z_min~%float32 z_max~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjectROIResult)))
  "Returns full string definition for message of type 'ObjectROIResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%ROI[] roi~%~%================================================================================~%MSG: alice_msgs/ROI~%int32 left ~%int32 top~%int32 right~%int32 bottom~%float32 x~%float32 y~%float32 z~%float32 z_min~%float32 z_max~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjectROIResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'roi) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjectROIResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjectROIResult
    (cl:cons ':roi (roi msg))
))
