// Generated by gencpp from file alice_msgs/MakePlan.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_MAKEPLAN_H
#define ALICE_MSGS_MESSAGE_MAKEPLAN_H

#include <ros/service_traits.h>


#include <alice_msgs/MakePlanRequest.h>
#include <alice_msgs/MakePlanResponse.h>


namespace alice_msgs
{

struct MakePlan
{

typedef MakePlanRequest Request;
typedef MakePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakePlan
} // namespace alice_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alice_msgs::MakePlan > {
  static const char* value()
  {
    return "9d98043111b72f254c7b31083eb22c8c";
  }

  static const char* value(const ::alice_msgs::MakePlan&) { return value(); }
};

template<>
struct DataType< ::alice_msgs::MakePlan > {
  static const char* value()
  {
    return "alice_msgs/MakePlan";
  }

  static const char* value(const ::alice_msgs::MakePlan&) { return value(); }
};


// service_traits::MD5Sum< ::alice_msgs::MakePlanRequest> should match 
// service_traits::MD5Sum< ::alice_msgs::MakePlan > 
template<>
struct MD5Sum< ::alice_msgs::MakePlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MakePlan >::value();
  }
  static const char* value(const ::alice_msgs::MakePlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MakePlanRequest> should match 
// service_traits::DataType< ::alice_msgs::MakePlan > 
template<>
struct DataType< ::alice_msgs::MakePlanRequest>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MakePlan >::value();
  }
  static const char* value(const ::alice_msgs::MakePlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alice_msgs::MakePlanResponse> should match 
// service_traits::MD5Sum< ::alice_msgs::MakePlan > 
template<>
struct MD5Sum< ::alice_msgs::MakePlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MakePlan >::value();
  }
  static const char* value(const ::alice_msgs::MakePlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MakePlanResponse> should match 
// service_traits::DataType< ::alice_msgs::MakePlan > 
template<>
struct DataType< ::alice_msgs::MakePlanResponse>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MakePlan >::value();
  }
  static const char* value(const ::alice_msgs::MakePlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_MAKEPLAN_H
