// Generated by gencpp from file alice_msgs/MakePlanRequest.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_MAKEPLANREQUEST_H
#define ALICE_MSGS_MESSAGE_MAKEPLANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alice_msgs
{
template <class ContainerAllocator>
struct MakePlanRequest_
{
  typedef MakePlanRequest_<ContainerAllocator> Type;

  MakePlanRequest_()
    : costmap_ros()
    , width(0)
    , height(0)
    , start(0)
    , goal(0)  {
    }
  MakePlanRequest_(const ContainerAllocator& _alloc)
    : costmap_ros(_alloc)
    , width(0)
    , height(0)
    , start(0)
    , goal(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _costmap_ros_type;
  _costmap_ros_type costmap_ros;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _start_type;
  _start_type start;

   typedef int32_t _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::alice_msgs::MakePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alice_msgs::MakePlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MakePlanRequest_

typedef ::alice_msgs::MakePlanRequest_<std::allocator<void> > MakePlanRequest;

typedef boost::shared_ptr< ::alice_msgs::MakePlanRequest > MakePlanRequestPtr;
typedef boost::shared_ptr< ::alice_msgs::MakePlanRequest const> MakePlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alice_msgs::MakePlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'alice_msgs': ['/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/src/alice_msgs/msg', '/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/devel/share/alice_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::MakePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::MakePlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::MakePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a6b528d357d7086cc62b1bf2dbac8be";
  }

  static const char* value(const ::alice_msgs::MakePlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a6b528d357d7086ULL;
  static const uint64_t static_value2 = 0xcc62b1bf2dbac8beULL;
};

template<class ContainerAllocator>
struct DataType< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alice_msgs/MakePlanRequest";
  }

  static const char* value(const ::alice_msgs::MakePlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] costmap_ros\n\
int32 width\n\
int32 height\n\
int32 start\n\
int32 goal\n\
";
  }

  static const char* value(const ::alice_msgs::MakePlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.costmap_ros);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MakePlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alice_msgs::MakePlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alice_msgs::MakePlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "costmap_ros[]" << std::endl;
    for (size_t i = 0; i < v.costmap_ros.size(); ++i)
    {
      s << indent << "  costmap_ros[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.costmap_ros[i]);
    }
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "start: ";
    Printer<int32_t>::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_MAKEPLANREQUEST_H
