// Generated by gencpp from file alice_msgs/MakePlanResponse.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_MAKEPLANRESPONSE_H
#define ALICE_MSGS_MESSAGE_MAKEPLANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alice_msgs
{
template <class ContainerAllocator>
struct MakePlanResponse_
{
  typedef MakePlanResponse_<ContainerAllocator> Type;

  MakePlanResponse_()
    : plan()  {
    }
  MakePlanResponse_(const ContainerAllocator& _alloc)
    : plan(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _plan_type;
  _plan_type plan;





  typedef boost::shared_ptr< ::alice_msgs::MakePlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alice_msgs::MakePlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MakePlanResponse_

typedef ::alice_msgs::MakePlanResponse_<std::allocator<void> > MakePlanResponse;

typedef boost::shared_ptr< ::alice_msgs::MakePlanResponse > MakePlanResponsePtr;
typedef boost::shared_ptr< ::alice_msgs::MakePlanResponse const> MakePlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alice_msgs::MakePlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'alice_msgs': ['/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/src/alice_msgs/msg', '/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/devel/share/alice_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::MakePlanResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::MakePlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::MakePlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d00db495743883c1d9a4cf3d0844ceac";
  }

  static const char* value(const ::alice_msgs::MakePlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd00db495743883c1ULL;
  static const uint64_t static_value2 = 0xd9a4cf3d0844ceacULL;
};

template<class ContainerAllocator>
struct DataType< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alice_msgs/MakePlanResponse";
  }

  static const char* value(const ::alice_msgs::MakePlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] plan\n\
\n\
\n\
";
  }

  static const char* value(const ::alice_msgs::MakePlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MakePlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alice_msgs::MakePlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alice_msgs::MakePlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "plan[]" << std::endl;
    for (size_t i = 0; i < v.plan.size(); ++i)
    {
      s << indent << "  plan[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.plan[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_MAKEPLANRESPONSE_H
