// Generated by gencpp from file alice_msgs/MemoryReadSrv.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_MEMORYREADSRV_H
#define ALICE_MSGS_MESSAGE_MEMORYREADSRV_H

#include <ros/service_traits.h>


#include <alice_msgs/MemoryReadSrvRequest.h>
#include <alice_msgs/MemoryReadSrvResponse.h>


namespace alice_msgs
{

struct MemoryReadSrv
{

typedef MemoryReadSrvRequest Request;
typedef MemoryReadSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MemoryReadSrv
} // namespace alice_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alice_msgs::MemoryReadSrv > {
  static const char* value()
  {
    return "d51d115d775c2a48b0344e7e96fb1a09";
  }

  static const char* value(const ::alice_msgs::MemoryReadSrv&) { return value(); }
};

template<>
struct DataType< ::alice_msgs::MemoryReadSrv > {
  static const char* value()
  {
    return "alice_msgs/MemoryReadSrv";
  }

  static const char* value(const ::alice_msgs::MemoryReadSrv&) { return value(); }
};


// service_traits::MD5Sum< ::alice_msgs::MemoryReadSrvRequest> should match 
// service_traits::MD5Sum< ::alice_msgs::MemoryReadSrv > 
template<>
struct MD5Sum< ::alice_msgs::MemoryReadSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MemoryReadSrv >::value();
  }
  static const char* value(const ::alice_msgs::MemoryReadSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MemoryReadSrvRequest> should match 
// service_traits::DataType< ::alice_msgs::MemoryReadSrv > 
template<>
struct DataType< ::alice_msgs::MemoryReadSrvRequest>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MemoryReadSrv >::value();
  }
  static const char* value(const ::alice_msgs::MemoryReadSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alice_msgs::MemoryReadSrvResponse> should match 
// service_traits::MD5Sum< ::alice_msgs::MemoryReadSrv > 
template<>
struct MD5Sum< ::alice_msgs::MemoryReadSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MemoryReadSrv >::value();
  }
  static const char* value(const ::alice_msgs::MemoryReadSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MemoryReadSrvResponse> should match 
// service_traits::DataType< ::alice_msgs::MemoryReadSrv > 
template<>
struct DataType< ::alice_msgs::MemoryReadSrvResponse>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MemoryReadSrv >::value();
  }
  static const char* value(const ::alice_msgs::MemoryReadSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_MEMORYREADSRV_H
