// Generated by gencpp from file alice_msgs/MemorySrv.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_MEMORYSRV_H
#define ALICE_MSGS_MESSAGE_MEMORYSRV_H

#include <ros/service_traits.h>


#include <alice_msgs/MemorySrvRequest.h>
#include <alice_msgs/MemorySrvResponse.h>


namespace alice_msgs
{

struct MemorySrv
{

typedef MemorySrvRequest Request;
typedef MemorySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MemorySrv
} // namespace alice_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alice_msgs::MemorySrv > {
  static const char* value()
  {
    return "0a4d3e78c1c53b7a4607e46a47b6c2da";
  }

  static const char* value(const ::alice_msgs::MemorySrv&) { return value(); }
};

template<>
struct DataType< ::alice_msgs::MemorySrv > {
  static const char* value()
  {
    return "alice_msgs/MemorySrv";
  }

  static const char* value(const ::alice_msgs::MemorySrv&) { return value(); }
};


// service_traits::MD5Sum< ::alice_msgs::MemorySrvRequest> should match 
// service_traits::MD5Sum< ::alice_msgs::MemorySrv > 
template<>
struct MD5Sum< ::alice_msgs::MemorySrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MemorySrv >::value();
  }
  static const char* value(const ::alice_msgs::MemorySrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MemorySrvRequest> should match 
// service_traits::DataType< ::alice_msgs::MemorySrv > 
template<>
struct DataType< ::alice_msgs::MemorySrvRequest>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MemorySrv >::value();
  }
  static const char* value(const ::alice_msgs::MemorySrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alice_msgs::MemorySrvResponse> should match 
// service_traits::MD5Sum< ::alice_msgs::MemorySrv > 
template<>
struct MD5Sum< ::alice_msgs::MemorySrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MemorySrv >::value();
  }
  static const char* value(const ::alice_msgs::MemorySrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MemorySrvResponse> should match 
// service_traits::DataType< ::alice_msgs::MemorySrv > 
template<>
struct DataType< ::alice_msgs::MemorySrvResponse>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MemorySrv >::value();
  }
  static const char* value(const ::alice_msgs::MemorySrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_MEMORYSRV_H
