// Generated by gencpp from file alice_msgs/MemoryReadSrvResponse.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_MEMORYREADSRVRESPONSE_H
#define ALICE_MSGS_MESSAGE_MEMORYREADSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alice_msgs
{
template <class ContainerAllocator>
struct MemoryReadSrvResponse_
{
  typedef MemoryReadSrvResponse_<ContainerAllocator> Type;

  MemoryReadSrvResponse_()
    : json()  {
    }
  MemoryReadSrvResponse_(const ContainerAllocator& _alloc)
    : json(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _json_type;
  _json_type json;





  typedef boost::shared_ptr< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MemoryReadSrvResponse_

typedef ::alice_msgs::MemoryReadSrvResponse_<std::allocator<void> > MemoryReadSrvResponse;

typedef boost::shared_ptr< ::alice_msgs::MemoryReadSrvResponse > MemoryReadSrvResponsePtr;
typedef boost::shared_ptr< ::alice_msgs::MemoryReadSrvResponse const> MemoryReadSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'alice_msgs': ['/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/src/alice_msgs/msg', '/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/devel/share/alice_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f859d01b8e3757110b53b06e823ec597";
  }

  static const char* value(const ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf859d01b8e375711ULL;
  static const uint64_t static_value2 = 0x0b53b06e823ec597ULL;
};

template<class ContainerAllocator>
struct DataType< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alice_msgs/MemoryReadSrvResponse";
  }

  static const char* value(const ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string json\n\
\n\
";
  }

  static const char* value(const ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MemoryReadSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alice_msgs::MemoryReadSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_MEMORYREADSRVRESPONSE_H
