// Generated by gencpp from file alice_msgs/MoveHead.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_MOVEHEAD_H
#define ALICE_MSGS_MESSAGE_MOVEHEAD_H

#include <ros/service_traits.h>


#include <alice_msgs/MoveHeadRequest.h>
#include <alice_msgs/MoveHeadResponse.h>


namespace alice_msgs
{

struct MoveHead
{

typedef MoveHeadRequest Request;
typedef MoveHeadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveHead
} // namespace alice_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alice_msgs::MoveHead > {
  static const char* value()
  {
    return "a19b17bdf8dab4d23fa8adb89a9e5e53";
  }

  static const char* value(const ::alice_msgs::MoveHead&) { return value(); }
};

template<>
struct DataType< ::alice_msgs::MoveHead > {
  static const char* value()
  {
    return "alice_msgs/MoveHead";
  }

  static const char* value(const ::alice_msgs::MoveHead&) { return value(); }
};


// service_traits::MD5Sum< ::alice_msgs::MoveHeadRequest> should match 
// service_traits::MD5Sum< ::alice_msgs::MoveHead > 
template<>
struct MD5Sum< ::alice_msgs::MoveHeadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MoveHead >::value();
  }
  static const char* value(const ::alice_msgs::MoveHeadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MoveHeadRequest> should match 
// service_traits::DataType< ::alice_msgs::MoveHead > 
template<>
struct DataType< ::alice_msgs::MoveHeadRequest>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MoveHead >::value();
  }
  static const char* value(const ::alice_msgs::MoveHeadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alice_msgs::MoveHeadResponse> should match 
// service_traits::MD5Sum< ::alice_msgs::MoveHead > 
template<>
struct MD5Sum< ::alice_msgs::MoveHeadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alice_msgs::MoveHead >::value();
  }
  static const char* value(const ::alice_msgs::MoveHeadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_msgs::MoveHeadResponse> should match 
// service_traits::DataType< ::alice_msgs::MoveHead > 
template<>
struct DataType< ::alice_msgs::MoveHeadResponse>
{
  static const char* value()
  {
    return DataType< ::alice_msgs::MoveHead >::value();
  }
  static const char* value(const ::alice_msgs::MoveHeadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_MOVEHEAD_H
