// Generated by gencpp from file alice_msgs/ObjectROIResult.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_OBJECTROIRESULT_H
#define ALICE_MSGS_MESSAGE_OBJECTROIRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <alice_msgs/ROI.h>

namespace alice_msgs
{
template <class ContainerAllocator>
struct ObjectROIResult_
{
  typedef ObjectROIResult_<ContainerAllocator> Type;

  ObjectROIResult_()
    : roi()  {
    }
  ObjectROIResult_(const ContainerAllocator& _alloc)
    : roi(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::alice_msgs::ROI_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::alice_msgs::ROI_<ContainerAllocator> >::other >  _roi_type;
  _roi_type roi;





  typedef boost::shared_ptr< ::alice_msgs::ObjectROIResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alice_msgs::ObjectROIResult_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectROIResult_

typedef ::alice_msgs::ObjectROIResult_<std::allocator<void> > ObjectROIResult;

typedef boost::shared_ptr< ::alice_msgs::ObjectROIResult > ObjectROIResultPtr;
typedef boost::shared_ptr< ::alice_msgs::ObjectROIResult const> ObjectROIResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alice_msgs::ObjectROIResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'alice_msgs': ['/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/src/alice_msgs/msg', '/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/devel/share/alice_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::ObjectROIResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::ObjectROIResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::ObjectROIResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e17122d90dfd682041714829c01ce576";
  }

  static const char* value(const ::alice_msgs::ObjectROIResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe17122d90dfd6820ULL;
  static const uint64_t static_value2 = 0x41714829c01ce576ULL;
};

template<class ContainerAllocator>
struct DataType< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alice_msgs/ObjectROIResult";
  }

  static const char* value(const ::alice_msgs::ObjectROIResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
ROI[] roi\n\
\n\
================================================================================\n\
MSG: alice_msgs/ROI\n\
int32 left \n\
int32 top\n\
int32 right\n\
int32 bottom\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 z_min\n\
float32 z_max\n\
";
  }

  static const char* value(const ::alice_msgs::ObjectROIResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectROIResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alice_msgs::ObjectROIResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alice_msgs::ObjectROIResult_<ContainerAllocator>& v)
  {
    s << indent << "roi[]" << std::endl;
    for (size_t i = 0; i < v.roi.size(); ++i)
    {
      s << indent << "  roi[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::alice_msgs::ROI_<ContainerAllocator> >::stream(s, indent + "    ", v.roi[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_OBJECTROIRESULT_H
