// Generated by gencpp from file alice_msgs/PointCloudFunctionResult.msg
// DO NOT EDIT!


#ifndef ALICE_MSGS_MESSAGE_POINTCLOUDFUNCTIONRESULT_H
#define ALICE_MSGS_MESSAGE_POINTCLOUDFUNCTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace alice_msgs
{
template <class ContainerAllocator>
struct PointCloudFunctionResult_
{
  typedef PointCloudFunctionResult_<ContainerAllocator> Type;

  PointCloudFunctionResult_()
    : min_point()
    , max_point()
    , point()  {
    }
  PointCloudFunctionResult_(const ContainerAllocator& _alloc)
    : min_point(_alloc)
    , max_point(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _min_point_type;
  _min_point_type min_point;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _max_point_type;
  _max_point_type max_point;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudFunctionResult_

typedef ::alice_msgs::PointCloudFunctionResult_<std::allocator<void> > PointCloudFunctionResult;

typedef boost::shared_ptr< ::alice_msgs::PointCloudFunctionResult > PointCloudFunctionResultPtr;
typedef boost::shared_ptr< ::alice_msgs::PointCloudFunctionResult const> PointCloudFunctionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alice_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'alice_msgs': ['/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/src/alice_msgs/msg', '/home/mega/Documents/AutoSysPE/pas/ros/catkin_ws/devel/share/alice_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63f2660951e11cc0788dcd78f585bfeb";
  }

  static const char* value(const ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63f2660951e11cc0ULL;
  static const uint64_t static_value2 = 0x788dcd78f585bfebULL;
};

template<class ContainerAllocator>
struct DataType< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alice_msgs/PointCloudFunctionResult";
  }

  static const char* value(const ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result\n\
geometry_msgs/Point[] min_point # for dimensions\n\
geometry_msgs/Point[] max_point # for dimensions\n\
geometry_msgs/Point[] point     # for single points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min_point);
      stream.next(m.max_point);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudFunctionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alice_msgs::PointCloudFunctionResult_<ContainerAllocator>& v)
  {
    s << indent << "min_point[]" << std::endl;
    for (size_t i = 0; i < v.min_point.size(); ++i)
    {
      s << indent << "  min_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.min_point[i]);
    }
    s << indent << "max_point[]" << std::endl;
    for (size_t i = 0; i < v.max_point.size(); ++i)
    {
      s << indent << "  max_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.max_point[i]);
    }
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICE_MSGS_MESSAGE_POINTCLOUDFUNCTIONRESULT_H
