# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from alice_msgs/ROI.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ROI(genpy.Message):
  _md5sum = "8eade1c15e9ba7247a93b357e0059c0f"
  _type = "alice_msgs/ROI"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 left 
int32 top
int32 right
int32 bottom
float32 x
float32 y
float32 z
float32 z_min
float32 z_max
"""
  __slots__ = ['left','top','right','bottom','x','y','z','z_min','z_max']
  _slot_types = ['int32','int32','int32','int32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left,top,right,bottom,x,y,z,z_min,z_max

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ROI, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left is None:
        self.left = 0
      if self.top is None:
        self.top = 0
      if self.right is None:
        self.right = 0
      if self.bottom is None:
        self.bottom = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.z_min is None:
        self.z_min = 0.
      if self.z_max is None:
        self.z_max = 0.
    else:
      self.left = 0
      self.top = 0
      self.right = 0
      self.bottom = 0
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.z_min = 0.
      self.z_max = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i5f().pack(_x.left, _x.top, _x.right, _x.bottom, _x.x, _x.y, _x.z, _x.z_min, _x.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.left, _x.top, _x.right, _x.bottom, _x.x, _x.y, _x.z, _x.z_min, _x.z_max,) = _get_struct_4i5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i5f().pack(_x.left, _x.top, _x.right, _x.bottom, _x.x, _x.y, _x.z, _x.z_min, _x.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.left, _x.top, _x.right, _x.bottom, _x.x, _x.y, _x.z, _x.z_min, _x.z_max,) = _get_struct_4i5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i5f = None
def _get_struct_4i5f():
    global _struct_4i5f
    if _struct_4i5f is None:
        _struct_4i5f = struct.Struct("<4i5f")
    return _struct_4i5f
