// Auto-generated. Do not edit!

// (in-package alice_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ROI = require('./ROI.js');

//-----------------------------------------------------------

class ObjectROIResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.roi = null;
    }
    else {
      if (initObj.hasOwnProperty('roi')) {
        this.roi = initObj.roi
      }
      else {
        this.roi = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ObjectROIResult
    // Serialize message field [roi]
    // Serialize the length for message field [roi]
    bufferOffset = _serializer.uint32(obj.roi.length, buffer, bufferOffset);
    obj.roi.forEach((val) => {
      bufferOffset = ROI.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ObjectROIResult
    let len;
    let data = new ObjectROIResult(null);
    // Deserialize message field [roi]
    // Deserialize array length for message field [roi]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.roi = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.roi[i] = ROI.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 36 * object.roi.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'alice_msgs/ObjectROIResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e17122d90dfd682041714829c01ce576';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    ROI[] roi
    
    ================================================================================
    MSG: alice_msgs/ROI
    int32 left 
    int32 top
    int32 right
    int32 bottom
    float32 x
    float32 y
    float32 z
    float32 z_min
    float32 z_max
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ObjectROIResult(null);
    if (msg.roi !== undefined) {
      resolved.roi = new Array(msg.roi.length);
      for (let i = 0; i < resolved.roi.length; ++i) {
        resolved.roi[i] = ROI.Resolve(msg.roi[i]);
      }
    }
    else {
      resolved.roi = []
    }

    return resolved;
    }
};

module.exports = ObjectROIResult;
